on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  pull_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: pull and build
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: 194.58.90.18
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            /root/stophp.sh &&
            cd ${{ vars.WORKING_DIRECTORY }} &&
            git pull &&
            npm run build &&
            /root/starthp.sh